// Generated by gencpp from file face/FaceSrvRequest.msg
// DO NOT EDIT!


#ifndef FACE_MESSAGE_FACESRVREQUEST_H
#define FACE_MESSAGE_FACESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face
{
template <class ContainerAllocator>
struct FaceSrvRequest_
{
  typedef FaceSrvRequest_<ContainerAllocator> Type;

  FaceSrvRequest_()
    : ctrl()  {
    }
  FaceSrvRequest_(const ContainerAllocator& _alloc)
    : ctrl(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ctrl_type;
  _ctrl_type ctrl;





  typedef boost::shared_ptr< ::face::FaceSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face::FaceSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceSrvRequest_

typedef ::face::FaceSrvRequest_<std::allocator<void> > FaceSrvRequest;

typedef boost::shared_ptr< ::face::FaceSrvRequest > FaceSrvRequestPtr;
typedef boost::shared_ptr< ::face::FaceSrvRequest const> FaceSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face::FaceSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face::FaceSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face::FaceSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face::FaceSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face::FaceSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face::FaceSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face::FaceSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face::FaceSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face::FaceSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d1f646efcbbf77c9bd2939709b82526";
  }

  static const char* value(const ::face::FaceSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d1f646efcbbf77cULL;
  static const uint64_t static_value2 = 0x9bd2939709b82526ULL;
};

template<class ContainerAllocator>
struct DataType< ::face::FaceSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face/FaceSrvRequest";
  }

  static const char* value(const ::face::FaceSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face::FaceSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ctrl\n\
";
  }

  static const char* value(const ::face::FaceSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face::FaceSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face::FaceSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face::FaceSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "ctrl: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ctrl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_MESSAGE_FACESRVREQUEST_H
